services:
  deepwiki:
    image: ghcr.io/charles1614/deepwiki:latest
    platform: linux/amd64
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: always

  claude-code:
    image: ghcr.io/charles1614/deepwiki/claude-code:latest
    platform: linux/amd64
    container_name: claude-code
    ports:
      - "2222:22"
      - "3001:3001"
    restart: always
